# -*- coding: utf-8 -*-
"""Startup Financial KPI Analysis .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KW67-i3i9ixvs_L-HaTK9PMZMua3HVWQ
"""

import pandas as pd
import numpy as np

df = pd.read_csv("SaaS-Sales.csv")
df["Order Date"] = pd.to_datetime(df["Order Date"])

df["Month"] = df["Order Date"].dt.to_period("M")

customer_first_purchase = df.groupby("Customer ID")["Order Date"].min().reset_index()

customer_first_purchase["Cohort Month"] = customer_first_purchase["Order Date"].dt.to_period("M")

df = df.merge(customer_first_purchase[["Customer ID","Cohort Month"]], on="Customer ID")

marketing_spend = {
    "AMER":50000,
    "EMEA":40000,
    "APAC":30000
}

df["Marketing Spend"] = df["Region"].map(marketing_spend)

new_customers = df.groupby("Month")["Customer ID"].nunique().reset_index()

monthly_revenue = df.groupby("Month")["Sales"].sum().reset_index()

print(monthly_revenue)

monthly_revenue["Expenses"] = 120000

monthly_revenue["Burn Rate"] = monthly_revenue["Expenses"] - monthly_revenue["Sales"]

monthly_customers = df.groupby("Month")["Customer ID"].nunique().reset_index()

monthly_customers.rename(columns={"Customer ID":"Customers"}, inplace=True)

monthly_marketing = df.groupby("Month")["Marketing Spend"].mean().reset_index()

cac_df = monthly_customers.merge(monthly_marketing, on="Month")

cac_df["CAC"] = cac_df["Marketing Spend"] / cac_df["Customers"]

total_revenue = df["Sales"].sum()

total_customers = df["Customer ID"].nunique()

arpu = total_revenue / total_customers

lifetime = 24

ltv = arpu * lifetime

avg_cac = cac_df["CAC"].mean()

ltv_cac_ratio = ltv / avg_cac

print("LTV:",ltv)
print("CAC:",avg_cac)
print("LTV:CAC Ratio:",ltv_cac_ratio)

latest_revenue = monthly_revenue["Sales"].iloc[-1]

run_rate = latest_revenue * 12

print("Annual Run Rate:",run_rate)

df["Order Month"] = df["Order Date"].dt.to_period("M")

cohort_data = df.groupby(["Cohort Month","Order Month"])["Customer ID"].nunique()

cohort_table = cohort_data.unstack(0)

print(cohort_table)

df_cleaned = df
df_cleaned.to_csv("saas_sales_cleaned_kpi.csv", index=False)